admins:
- shirohasuki
- Mikemy666
- SJM946
- zhejianguk
- daiyongyuan
github:
  branch: main
  content_dir: content
  repo: DangoSys/documents
site:
  default_locale: en
  supported_locales:
  - en
  - zh
  title: Buckyball Documents
