site:
  title: "Buckyball Documents"
  default_locale: "en"
  supported_locales:
    - "en"
    - "zh"

admins:
  - "shirohasuki"

github:
  repo: "DangoSys/documents"
  branch: "main"
  content_dir: "content"
